### ISSUE TITLE
error with example/main.js

### ISSUE THREAD

**Issue by youngtt** [liangzeng/cqrs#2]
young:dist young$ node example/main.js

/Users/young/Dev/X/3.2/event-store/node_modules/cqrs/dist/lib/ActorListener.js:84
                    _this.myDomain.get(listener.actorType, listener.actorId, f
                                  ^
TypeError: Cannot read property 'get' of undefined
    at /Users/young/Dev/X/3.2/event-store/node_modules/cqrs/dist/lib/ActorListener.js:84:35
    at Array.forEach (native)
    at ActorListener.pub (/Users/young/Dev/X/3.2/event-store/node_modules/cqrs/dist/lib/ActorListener.js:83:27)
    at EventBus.<anonymous> (/Users/young/Dev/X/3.2/event-store/node_modules/cqrs/dist/lib/Domain.js:128:51)
    at EventBus.emit (events.js:129:20)
    at EventBus.__publish (/Users/young/Dev/X/3.2/event-store/node_modules/cqrs/dist/lib/EventBus.js:52:22)
    at Object.publisher (/Users/young/Dev/X/3.2/event-store/node_modules/cqrs/dist/lib/EventBus.js:29:19)
    at process (/Users/young/Dev/X/3.2/event-store/node_modules/eventstore/lib/eventDispatcher.js:38:18)
    at next (/Users/young/Dev/X/3.2/event-store/node_modules/eventstore/lib/eventDispatcher.js:58:7)
    at trigger (/Users/young/Dev/X/3.2/event-store/node_modules/eventstore/lib/eventDispatcher.js:62:5)

**Comment by liangzeng** [comment]
@youngtt  thanks , fixed.
publish v0.8.6
