### ISSUE TITLE
Error when creating Domain with mongodb store

### ISSUE THREAD

**Issue by youngtt** [liangzeng/cqrs#3]
```javascript
var Domain = require('cqrs').Domain;
var domain = new Domain(options);
```
**No error** when options = {}  ie. using in-memory db

The following **error when using mongodb** (v3.0.2) with options = { type: 'mongodb', host: 'localhost', timeout: 10000 }
```
/Users/young/Dev/X/3.2/service-eventstore/node_modules/mongodb/lib/server.js:274
      process.nextTick(function() { throw err; })
                                          ^
TypeError: Cannot read property 'maxWriteBatchSize' of null
    at new ServerCapabilities (/Users/young/Dev/X/3.2/service-eventstore/node_modules/mongodb/lib/topology_base.js:98:40)
    at Server.capabilities (/Users/young/Dev/X/3.2/service-eventstore/node_modules/mongodb/lib/server.js:300:26)
    at Collection.listIndexes (/Users/young/Dev/X/3.2/service-eventstore/node_modules/mongodb/lib/collection.js:1094:29)
    at Db.indexInformation (/Users/young/Dev/X/3.2/service-eventstore/node_modules/mongodb/lib/db.js:1217:25)
    at Db.ensureIndex (/Users/young/Dev/X/3.2/service-eventstore/node_modules/mongodb/lib/db.js:778:8)
    at Collection.ensureIndex (/Users/young/Dev/X/3.2/service-eventstore/node_modules/mongodb/lib/collection.js:1133:13)
    at finish (/Users/young/Dev/X/3.2/service-eventstore/node_modules/eventstore/lib/databases/mongodb.js:87:21)
    at /Users/young/Dev/X/3.2/service-eventstore/node_modules/eventstore/lib/databases/mongodb.js:108:7
    at /Users/young/Dev/X/3.2/service-eventstore/node_modules/mongodb/lib/db.js:206:5
    at connectHandler (/Users/young/Dev/X/3.2/service-eventstore/node_modules/mongodb/lib/server.js:272:7)
```

**Comment by liangzeng** [comment]
@youngtt  please see  https://github.com/liangzeng/cqrs#step-1--create-a-domain

**Comment by youngtt** [comment]
Commenting out the duplicated call to es.init() in EventBus.js removes this error.
https://github.com/liangzeng/cqrs/blob/master/src/lib/EventBus.js#L17

```javascript
class EventBus extends EventEmitter {

    constructor(eventstore) {
        this.es = eventstore;
        this.es.useEventPublisher((evt, cb) => {
            this.__publish(evt);
        });
        this.es.init();
    }
```

Also resolves #4

**Comment by liangzeng** [comment]
@youngtt thanks  , look  https://github.com/liangzeng/cqrs/tree/0.9.0

**Comment by youngtt** [comment]
@liangzeng thanks :)
